# Generated by Django 5.2 on 2025-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sgn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=25)),
                ('em', models.EmailField(max_length=254)),
                ('ps', models.CharField(max_length=16)),
            ],
        ),
    ]
