# Generated by Django 5.2 on 2025-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=25)),
                ('des', models.TextField()),
                ('l1', models.TextField()),
                ('in1', models.TextField()),
                ('in2', models.TextField()),
                ('in3', models.TextField()),
            ],
        ),
    ]
