# Generated by Django 5.2 on 2025-05-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0002_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pim', models.FileField(upload_to='pic')),
                ('ttl', models.CharField(default=0, max_length=25)),
                ('ds', models.TextField()),
                ('lst', models.TextField()),
                ('in1', models.CharField(max_length=25)),
                ('in2', models.CharField(max_length=25)),
                ('in3', models.CharField(max_length=25)),
            ],
        ),
    ]
