# Generated by Django 5.2 on 2025-05-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajapp', '0003_item_tbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg_tbl',
        ),
        migrations.DeleteModel(
            name='Sgn',
        ),
    ]
